# Blog settings
title: Jake Lee's Programming Blog
email: blog@jakelee.co.uk
description: Mostly Android tutorials & tips, with a little bit of web dev / tooling.
baseurl: ""
url: "https://blog.jakelee.co.uk"
permalink: /:title/
show_excerpts: true

# Theme settings
theme: minima
paginate: 10
paginate_path: page/:num/
twitter_username: JakeLeeUK
github_username: JakeSteam
linkedin_username: Jake-Lee
stackoverflow_username: Jake-Lee
stackoverflow_id: 608312
utterances_repo: "JakeSteam/blog-programming"
rss: RSS
main_url: https://jakelee.co.uk

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Analytics settings
google_analytics: UA-220119060-1

