# Blog settings
title: Jake Lee on Software
email: blog@jakelee.co.uk
description: Android tutorials, web development tips, and general software-y / web-y things!
baseurl: ""
url: "https://blog.jakelee.co.uk"
permalink: /:title/
show_excerpts: true
timezone: Europe/London

# Theme settings
theme: minima
paginate: 10
paginate_path: page/:num/
twitter_username: JakeLeeUK
github_username: JakeSteam
linkedin_username: Jake-Lee
stackoverflow_username: Jake-Lee
stackoverflow_id: 608312
giscus_repo: JakeSteam/blog-programming
giscus_repo_id: MDEwOlJlcG9zaXRvcnkzNTk5Mzc1OTM=
giscus_category: Comments
giscus_category_id: DIC_kwDOFXQ2Oc4CQ06o
rss: RSS

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Analytics settings
google_analytics: UA-220119060-1

