# Blog settings
title: Jake Lee Programming Blog
email: blog@jakelee.co.uk
description: Mostly Android tutorials & tips, with a little bit of web dev / tooling. Now on Jekyll! 
baseurl: ""
url: ""
permalink: /:title/
show_excerpts: true

# Theme settings
theme: minima
paginate: 5
paginate_path: page/:num/
twitter_username: JakeLeeUK
github_username: JakeSteam
linkedin_username: Jake-Lee
rss: RSS

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Analytics settings
google_analytics: UA-220119060-1

